{{pillar['headers']['salt']['file']}}
{%- from 'gitlab/defaults.yaml' import rawmap with context -%}
{%- set datamap = salt['grains.filter_by'](rawmap, merge=salt['pillar.get']('gitlab:lookup')) -%}

{%- set gl_home = salt['user.info'](datamap.user.name|default('git')).home|default('/home/' ~ datamap.user.name|default('git')) -%}
{%- set gl_user = datamap.user.name|default('git') -%}
{%- set gl_domain = salt['pillar.get']('gitlab:domain', salt['grains.get']('fqdn')) -%}

# GitLab user. git by default
user: {{ gl_user }}

# Url to gitlab instance. Used for api calls. Should end with a slash.
{%- if salt['pillar.get']('gitlab:https', false) %}
#gitlab_url: "https://{{ gl_domain }}/" ## broken for now
gitlab_url: "https://127.0.0.1/"
{% else %}
#gitlab_url: "http://{{ gl_domain }}/" # broken for now
gitlab_url: "https://127.0.0.1/"
{% endif %}

http_settings:
#  user: someone
#  password: somepass
{%- if salt['pillar.get']('gitlab:shell:ca_file', false) %}
  ca_file: {{salt['pillar.get']('gitlab:shell:ca_file') }}
{%- endif %}
{%- if salt['pillar.get']('gitlab:shell:ca_path', false) %}
  ca_path: {{ salt['pillar.get']('gitlab:shell:ca_path') }}
{%- endif %}
  #self_signed_cert: {{ salt['pillar.get']('gitlab:shell:self_signed_cert', false) }}
  self_signed_cert: True

# Repositories path
# Give the canonicalized absolute pathname,
# REPOS_PATH MUST NOT CONTAIN ANY SYMLINK!!!
# Check twice that none of the components is a symlink, including "/home".
repos_path: "{{ gl_home }}/repositories"

# File used as authorized_keys for gitlab user
auth_file: "{{ gl_home }}/.ssh/authorized_keys"

# Redis settings used for pushing commit notices to gitlab
redis:
  bin: /usr/bin/redis-cli
  host: localhost
  port: 6379
  # socket: /tmp/redis.socket # Only define this if you want to use sockets
  namespace: resque:gitlab

# Log file.
# Default is gitlab-shell.log in the root directory.
# log_file: "/home/git/gitlab-shell/gitlab-shell.log"

# Log level. INFO by default
log_level: {{ datamap.gitlab.shell.loglevel|default('INFO') }}

# Audit usernames.
# Set to true to see real usernames in the logs instead of key ids, which is easier to follow, but
# incurs an extra API call on every gitlab-shell command.
audit_usernames: {{ datamap.gitlab.shell.audit_usernames|default(False) }}
